name: WeatherWorkflow
on:
  schedule:
    # Runs at every 5-minute interval
    - cron: '0 7 * * 1-5'

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # You can specify the exact version if needed

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    # Step 4: Run main.py script
    - name: Run main.py
      env:
        API_KEY: ${{ secrets.WEATHER_KEY }} 

      run: |
        python main.py
      
